### ISSUE TITLE
convoy-nfs stuck initializing, and without socket created

### ISSUE THREAD

**Issue by ClementVidal** [rancher/convoy#96]
Rancher Version: 
**1.0.0**

Docker Version: 
**1.10.3**

OS: 
**Centos7**

I'm trying to use convoy command line to list all the volume under a given convoy-nfs stack.
The point is that the convoy socket seams to get removed right after convoy-nfs startup:

Steps to reproduce:

Deploy a convoy-nfs stack, and watch the log
According to the log of the convoy-nfs container in the convoy-nfs service, 
the socket was created:

> Registering convoy socket at /var/run/convoy-convoy-nfs.sock

After that, convoy-nfs mount the nfs volume:

> Mounting nfs. Command: mount -t nfs  mynfsserver.net:/home/bob/convoy/ /var/lib/rancher/convoy/convoy-nfs-9bf7ea79-c264-4750-8fe8-6432a4fd590e/mnt

It then register all the API endpoints, so everything seams to be fine,
but the ultimate log line tell me that the socket was removed:

> Remove previous sockfile at /host/var/run/convoy-convoy-nfs.sock

And within the convoy-nfs container, this socket effectively does not exist.
**This prevent me from being able to start the convoy command line has it need the convoy socket.**

On more thing:
ALL the service in the convoy-nfs stack are in an "_initializing_" state, and apparently wants to stay in this state :)

And one last thing:
Event with that, convoy-nfs seams to work: I'm able create new volume in my storage pool which are effectively on my nfs drive ....

And a bonus question: 
Is it plan to have a support for snapshoting, backup and restoration in rancher server ?

Thanks !

**Comment by Berndinox** [comment]
Got the same issue when installing localy and running:

`convoy daemon --drivers vfs --driver-opts vfs.path=/data`

it's stuck after:
`DEBU[0000] Registering plugin handler POST, /VolumeDriver.Path  pkg=daemon`
after aborting there is the log entry:

```
DEBU[0254] Cleaning up environment...                    pkg=daemon
ERRO[0254] http server erroraccept unix /var/run/convoy/convoy.sock: use of closed network connection  pkg=daemon
```

**Comment by ClementVidal** [comment]
I think we probably are probably facing a slightly different thing:
I do not have this _"http server erroraccept"_ error

I guess that your convoy stack is not working at all ?

In my setup the convoy stack is working, but there is no convoy socket: it get removed right after startup

**Comment by cjellick** [comment]
@ClementVidal can you provide the full logs for one of your convoy-agent containers? If its very long and repetitive, then I don't need the whole thing, just the last 1000 lines should do. 

That line:
```
Remove previous sockfile at /host/var/run/convoy-convoy-nfs.sock
```
occurs when the container restarts, so it seems that the containers are flapping for some reason.

**Comment by ClementVidal** [comment]
@cjellick here it is:

This is the log of a container in the convoy-nfs service.

```
4/8/2016 5:18:05 PMWaiting for metadata
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/1171/ns/mnt -F -- /var/lib/docker/devicemapper/mnt/1e822e26046214dc5988a1421c2e2dd53a60a3b63885d6a1a3c2f4f5e308cb03/rootfs/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a -- /launch volume-agent-nfs-internal 1171]"
4/8/2016 5:18:06 PMRegistering convoy socket at /var/run/convoy-convoy-nfs.sock
4/8/2016 5:18:06 PMMounting at: /var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a/mnt
4/8/2016 5:18:06 PMMounting nfs. Command: mount -t nfs  clement-vidal.fr:/home/cvidal/convoy/test /var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a/mnt
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Got: drivers [vfs]"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a/mnt]"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Got: ignore-docker-delete true"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Got: create-on-docker-mount true"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-nfs.sock daemon --drivers=vfs --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a/mnt --ignore-docker-delete=true --create-on-docker-mount=true --root=/var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a]"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-nfs-81c5993f-5222-4021-958e-88cf558f5c3a"
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering GET, /info" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering GET, /volumes/" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering GET, /backups/list" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering POST, /backups/create" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering DELETE, /backups" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon
4/8/2016 5:18:06 PMtime="2016-04-08T15:18:06Z" level=warning msg="Remove previous sockfile at /host/var/run/convoy-convoy-nfs.sock" pkg=daemon
```

**Comment by cjellick** [comment]
@ClementVidal and does
```
docker volume create -d convoy-nfs --name test1
```
fail or succeed?

**Comment by ClementVidal** [comment]
Yes it succeed, the volume is created and visible in the ranche storage pools (tagged as '_inactive_') !

**Comment by cjellick** [comment]
ok, cool. What is the _exact_ command you are running that does fail?

**Comment by ClementVidal** [comment]
If i run on the host of the convoy-agent:
`docker volume create -d convoy-nfs --name test1`
Then everythings works fine, but

if i run (still from the host):
`convoy -s /var/run/convoy-convoy-nfs.sock list`
I get this error:

```
ERRO[0000] Get http:///var/run/convoy-convoy-nfs.sock/v1/volumes/list: dial unix /var/run/convoy-convoy-nfs.sock: permission denied 
{
	"Error": "Get http:///var/run/convoy-convoy-nfs.sock/v1/volumes/list: dial unix /var/run/convoy-convoy-nfs.sock: permission denied"
}
```

I must be misunderstand something

**Comment by ClementVidal** [comment]
Okay i get it, it's related to permissions:
` convoy -s /var/run/convoy-convoy-nfs.sock list`
does not work,  but :
`sudo /usr/local/bin/convoy -s /var/run/convoy-convoy-nfs.sock list`
work just fine !

I'm i supposed to use sudo or to change the socket permissions ?

Thanks a lot !

**Comment by saphoooo** [comment]
I have the same kind of issue as described: stack convoy-nfs is in initializing state, even if log seem good and convoy works fine.
I'm on AWS with convoy-nfs on EFS, RancherOS 4.5.0 and Rancher 1.1.0-dev3.
Only thing I've noticed in the logs:

```
7/9/2016 12:22:51 AMtime="2016-07-08T22:22:51Z" level=error msg="Handler for GET /volumes/list returned error: Volume list changed for volume 7ee28050efd0ef3731377037cbc8da69c0cab633ede6c753cee68b17f6107d1f" pkg=daemon
7/9/2016 12:22:51 AMtime="2016-07-08T22:22:51Z" level=error msg="invalid character 'V' looking for beginning of value"
```

And I wonder if there no something with healthckeck en EFS, but not sure.

**Comment by saphoooo** [comment]
Maybe the issue is in convoy-nfs storage pool:

```
7/9/2016 1:09:14 PMWaiting for metadata
7/9/2016 1:09:14 PMtime="2016-07-09T11:09:14Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
7/9/2016 1:09:15 PMtime="2016-07-09T11:09:15Z" level=info msg="Socket file: /host/var/run/convoy-convoy-nfs.sock"
7/9/2016 1:09:15 PMtime="2016-07-09T11:09:15Z" level=info msg="Initializing event router" workerCount=10
7/9/2016 1:09:15 PMtime="2016-07-09T11:09:15Z" level=info msg="Connection established"
7/9/2016 1:09:20 PMtime="2016-07-09T11:09:20Z" level=debug msg="storagepool event [65619704-c380-4c20-8aaa-3fa8b489e2fb 4fed29e7-3d9b-4aac-8890-e488aeb2d9c8]"
7/9/2016 1:53:00 PMtime="2016-07-09T11:53:00Z" level=debug msg="Processing event." event="{\"id\":\"64db65c2-52e8-4f96-8c5a-034be0157377\",\"name\":\"storage.volume.activate\",\"replyTo\":\"reply.6479617326003375288\",\"resourceId\":\"1vspm182\",\"resourceType\":\"volumeStoragePoolMap\",\"publisher\":null,\"transitioning\":null,\"transitioningMessage\":null,\"transitioningInternalMessage\":null,\"previousIds\":null,\"previousNames\":null,\"data\":{\"volumeStoragePoolMap\":{\"created\":1468065179000,\"description\":null,\"data\":{},\"id\":182,\"uuid\":\"4aaf5118-9a79-4517-a80b-9d4be0b8c7c4\",\"removed\":null,\"kind\":\"volumeStoragePoolMap\",\"storagePoolId\":7,\"removeTime\":null,\"volumeId\":183,\"name\":null,\"state\":\"activating\",\"type\":\"volumeStoragePoolMap\",\"volume\":{\"created\":1468065179000,\"format\":null,\"description\":null,\"data\":{\"fields\":{\"isHostPath\":false,\"driver\":\"convoy-nfs\"}},\"uri\":\"convoy-nfs:///var/lib/rancher/convoy/convoy-nfs-d7317131-dbc7-4df8-b93d-934fe4a55112/mnt/a3d42b24ef37a21c797270f38c649553e1e475541ede0e7c18e7025f082ee04d\",\"id\":183,\"accountId\":5,\"uuid\":\"ed0f22ba-5e67-481e-b365-18a925961eaf\",\"deviceNumber\":-1,\"hostId\":null,\"removed\":null,\"zoneId\":1,\"instanceId\":null,\"kind\":\"volume\",\"externalId\":\"a3d42b24ef37a21c797270f38c649553e1e475541ede0e7c18e7025f082ee04d\",\"imageId\":null,\"offeringId\":null,\"accessMode\":null,\"allocationState\":\"active\",\"removeTime\":null,\"physicalSizeMb\":null,\"virtualSizeMb\":null,\"attachedState\":\"inactive\",\"name\":\"a3d42b24ef37a21c797270f38c649553e1e475541ede0e7c18e7025f082ee04d\",\"state\":\"activating\",\"type\":\"volume\",\"offering\":null,\"instance\":null,\"storagePools\":[{\"created\":1467924579000,\"description\":null,\"data\":{},\"driverName\":\"convoy-nfs\",\"id\":7,\"agentId\":39,\"accountId\":5,\"uuid\":\"974d66e6-5123-41f7-8abf-b7b80eea5e2a\",\"removed\":null,\"zoneId\":1,\"kind\":\"storagePool\",\"externalId\":\"convoy-nfs\",\"removeTime\":null,\"physicalTotalSizeMb\":null,\"external\":false,\"virtualTotalSizeMb\":null,\"volumeAccessMode\":null,\"name\":\"convoy-nfs\",\"state\":\"active\",\"type\":\"storagePool\"}],\"image\":null},\"storagePool\":{\"created\":1467924579000,\"description\":null,\"data\":{},\"driverName\":\"convoy-nfs\",\"id\":7,\"agentId\":39,\"accountId\":5,\"uuid\":\"974d66e6-5123-41f7-8abf-b7b80eea5e2a\",\"removed\":null,\"zoneId\":1,\"kind\":\"storagePool\",\"externalId\":\"convoy-nfs\",\"removeTime\":null,\"physicalTotalSizeMb\":null,\"external\":false,\"virtualTotalSizeMb\":null,\"volumeAccessMode\":null,\"name\":\"convoy-nfs\",\"state\":\"active\",\"type\":\"storagePool\"}}},\"time\":1468065180318,\"timeoutMillis\":15000,\"transitioningProgress\":null,\"context\":{\"processId\":\"8688\",\"logicPath\":\"volume.activate->(VolumeActivate)->volumestoragepoolmap.activate->(VolumeStoragePoolMapActivate)\",\"logicName\":\"VolumeStoragePoolMapActivate\",\"prettyResource\":\"volume:183->volumeStoragePoolMap:182\",\"processName\":\"volumestoragepoolmap.activate\",\"topResourceType\":\"volume\",\"resouceId\":\"182\",\"resouceType\":\"volumeStoragePoolMap\",\"prettyProcess\":\"volume.activate->volumestoragepoolmap.activate\",\"topProcessName\":\"volume.activate\",\"topResourceId\":\"183\",\"processUuid\":\"1674bf93-371e-4866-938d-45e5bc89327e\"}}"
7/9/2016 1:53:00 PMtime="2016-07-09T11:53:00Z" level=info msg="Received and ignoring event: Name: storage.volume.activate, Event Id: 64db65c2-52e8-4f96-8c5a-034be0157377, Resource Id: 1vspm182"
7/9/2016 1:53:00 PMtime="2016-07-09T11:53:00Z" level=info msg="Reply: &{Resource:{Id: Type: Links:map[] Actions:map[]} Data:map[] Name:reply.6479617326003375288 PreviousIds:[64db65c2-52e8-4f96-8c5a-034be0157377] Publisher: ResourceId:1vspm182 ResourceType:volume Time:0 Transitioning: TransitioningInternalMessage: TransitioningMessage: TransitioningProgress:0}"
7/9/2016 2:16:15 PMtime="2016-07-09T12:16:15Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:16:50 PMtime="2016-07-09T12:16:50Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:17:25 PMtime="2016-07-09T12:17:25Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:18:00 PMtime="2016-07-09T12:18:00Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:18:35 PMtime="2016-07-09T12:18:35Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:19:10 PMtime="2016-07-09T12:19:10Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:19:45 PMtime="2016-07-09T12:19:45Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:20:20 PMtime="2016-07-09T12:20:20Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:20:55 PMtime="2016-07-09T12:20:55Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:21:30 PMtime="2016-07-09T12:21:30Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:22:05 PMtime="2016-07-09T12:22:05Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:22:40 PMtime="2016-07-09T12:22:40Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:23:15 PMtime="2016-07-09T12:23:15Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:23:50 PMtime="2016-07-09T12:23:50Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:24:25 PMtime="2016-07-09T12:24:25Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:25:00 PMtime="2016-07-09T12:25:00Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:25:35 PMtime="2016-07-09T12:25:35Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:26:10 PMtime="2016-07-09T12:26:10Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:26:45 PMtime="2016-07-09T12:26:45Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:27:20 PMtime="2016-07-09T12:27:20Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
7/9/2016 2:27:55 PMtime="2016-07-09T12:27:55Z" level=error msg="Error while reading host info [Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout]"
```

**Comment by gmeans** [comment]
I'm experiencing the same issues on AWS w/ EFS. I launch convoy-nfs from the catalog and the containers remain in "Initializing".

I ran the commands suggested by @cjellick successfully, and if I refresh the Storage page I see the test volumes appear in an Inactive state.

Does this imply convoy-nfs is actually working and the issue is just related to the containers not finishing start up?

**Comment by cjellick** [comment]
What container isnt finishing startup @gmeans ?

**Comment by gmeans** [comment]
@cjellick all 3 convoy-nfs containers and the convoy-nfs-storagepool container each are stuck in "initializing".

**Comment by cjellick** [comment]
Can you share some of the logs from the storage pool container and one of the volume containers?

**Comment by gmeans** [comment]
@cjellick sorry for the late response. I switched over to Convoy-EFS and haven't had an issue yet. I had already torn down the other setup.

**Comment by bacheson** [comment]
+1 just hangs

time="2016-08-16T21:20:26Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/1503/ns/mnt -F -- /var/lib/docker/overlay/aa4ca647a77e71eaee288014a09b6d0ad42def5145e2b0b92fb3629c3201b7e3/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778 -- /launch volume-agent-nfs-internal 1503]" 
Registering convoy socket at /var/run/convoy-fileserver.sock
Mounting at: /var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778/mnt
Mounting nfs. Command: mount -t nfs  10.240.0.5:/mnt/fileserver /var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778/mnt
time="2016-08-16T21:20:26Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck" 
time="2016-08-16T21:20:26Z" level=info msg="Got: ignore-docker-delete true" 
time="2016-08-16T21:20:26Z" level=info msg="Got: create-on-docker-mount true" 
time="2016-08-16T21:20:26Z" level=info msg="Got: root /var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778" 
time="2016-08-16T21:20:26Z" level=info msg="Got: drivers [vfs]" 
time="2016-08-16T21:20:26Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778/mnt]" 
time="2016-08-16T21:20:26Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-fileserver.sock daemon --ignore-docker-delete=true --create-on-docker-mount=true --root=/var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778 --drivers=vfs --driver-opts=vfs.path=/var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778/mnt]" 
time="2016-08-16T21:20:26Z" level=debug msg="Creating config at /var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/fileserver-93667a92-f0eb-4090-935a-d35edbb54778" 
time="2016-08-16T21:20:26Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete 
time="2016-08-16T21:20:26Z" level=debug msg="Registering GET, /info" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering GET, /volumes/" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering GET, /backups/list" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering POST, /backups/create" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering DELETE, /backups" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon 
time="2016-08-16T21:20:26Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon

**Comment by jalona** [comment]
Containers are stuck in "Initializing" state

Centos 7
docker-common-1.10.3-46.el7.centos.10.x86_64
Rancher	v1.1.2
Cattle	v0.165.8
User Interface	v1.1.12
Rancher Compose	v0.8.6

convoy-agent:v0.9.0

convoy-nfs_convoy-nfs_1
```

19.08.2016 10:54:42Waiting for metadata
19.08.2016 10:54:43time="2016-08-19T07:54:43Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/30084/ns/mnt -F -- /var/lib/docker/devicemapper/mnt/5ab8f04004806f012b01f1775bb4725806c10ba1299dc263f52bd57a07931ff7/rootfs/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570 -- /launch volume-agent-nfs-internal 30084]"
19.08.2016 10:54:44Registering convoy socket at /var/run/convoy-convoy-nfs.sock
19.08.2016 10:54:44Mounting at: /var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570/mnt
19.08.2016 10:54:44Mounting nfs. Command: mount -t nfs -o nfsvers=4 it-portal.homecredit.ru:/ /var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570/mnt
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=info msg="Got: drivers [vfs]"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570/mnt]"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=info msg="Got: ignore-docker-delete true"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=info msg="Got: create-on-docker-mount true"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-nfs.sock daemon --root=/var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570 --drivers=vfs --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570/mnt --ignore-docker-delete=true --create-on-docker-mount=true]"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-nfs-3c2361d1-f956-48d4-a65a-e67819b63570"
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering GET, /info" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering GET, /volumes/" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering GET, /backups/list" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering POST, /backups/create" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering DELETE, /backups" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon
19.08.2016 10:54:44time="2016-08-19T07:54:44Z" level=warning msg="Remove previous sockfile at /host/var/run/convoy-convoy-nfs.sock" pkg=daemon
```

convoy-nfs_convoy-nfs-storagepool_1
```
19.08.2016 10:54:50Waiting for metadata
19.08.2016 10:54:50time="2016-08-19T07:54:50Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
19.08.2016 10:54:50time="2016-08-19T07:54:50Z" level=info msg="Socket file: /host/var/run/convoy-convoy-nfs.sock"
19.08.2016 10:54:50time="2016-08-19T07:54:50Z" level=info msg="Initializing event router" workerCount=10
19.08.2016 10:54:50time="2016-08-19T07:54:50Z" level=info msg="Connection established"
19.08.2016 10:54:55time="2016-08-19T07:54:55Z" level=debug msg="storagepool event [dca9bdfc-b2ed-4fc7-98cb-0d5030b0729b 2900d904-5f79-41bd-ada2-b52193a45ee0]"
```

**Comment by yasker** [comment]
@bacheson @jalona Both log in your part looks fine. 

What you can try is mount the NFS manually on the host you're running Convoy on, which should work in order for Convoy to work.

And when you talk about "container hang", are you talking about creating new container, or just `convoy-nfs` stack hanging?

**Comment by yasker** [comment]
Also, can you try if create a new container with new volume and convoy-nfs works?

**Comment by ebuildy** [comment]
@yasker I think this is what happens:

![](http://b3.ms/gPG9Y00BM7JQ)

No mount is really created (but it's possible to manually mount something). How can I help to debug this?

Thanks,

**Comment by yasker** [comment]
@ebuildy Do you mean you didn't see any mount point for EFS server on the host?

Logs will be helpful as well.

**Comment by ebuildy** [comment]
@yasker my logs are similar to what @jalona just posted here. 

````
 
15/09/2016 20:54:45Waiting for metadata
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/27886/ns/mnt -F -- /var/lib/docker/devicemapper/mnt/20540d7ff9ff751def72553cf6745c1b738c47efae5aae27f6af7ae4c9b2a0e6/rootfs/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6 -- /launch volume-agent-efs-internal 27886]"
15/09/2016 20:54:46Registering convoy socket at /var/run/convoy-convoy-efs.sock
15/09/2016 20:54:46Mounting at: /var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6/mnt
15/09/2016 20:54:46Mounting nfs. Command: mount -t nfs -o nfsvers=4.1 eu-west-1a.fs-5785709e.efs.eu-west-1.amazonaws.com:/ /var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6/mnt
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6/mnt]"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Got: ignore-docker-delete true"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Got: create-on-docker-mount true"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Got: drivers [vfs]"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-efs.sock daemon --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6/mnt --ignore-docker-delete=true --create-on-docker-mount=true --root=/var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6 --drivers=vfs]"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Found existing config. Ignoring command line opts, loading config from /var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6"
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering GET, /volumes/" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering GET, /backups/list" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering GET, /info" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering POST, /backups/create" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering DELETE, /backups" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon
15/09/2016 20:54:46time="2016-09-15T18:54:46Z" level=warning msg="Remove previous sockfile at /host/var/run/convoy-convoy-efs.sock" pkg=daemon
````

List mounts:

````
[ec2-user@node-1 ~]$ mount
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
/dev/xvda1 on / type ext4 (rw,noatime,data=ordered)
devtmpfs on /dev type devtmpfs (rw,relatime,size=3821140k,nr_inodes=955285,mode=755)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /cgroup/perf_event type cgroup (rw,relatime,perf_event)
````

There is the /var/lib/rancher/convoy/convoy-efs-f454ef6e-dc2a-4810-89a2-051b3a90c9e6 folder but mnt folder is empty!

**Comment by npjonath** [comment]
got the same problem here. 

Reproduction : 

1. Run fresh instance of rancher 1.2.0-pre3 on my localmachine.
2. Create two fresh instance of amazon linux EC2 hosts. (both using same network an security group options)
3. Connect on each host using SSH
4. Install docker (1.11.2) on each host
5. Run rancher agent using the link given by rancher in "add host" menu.
6. Start convoy-EFS using information from Amazon Elastic Files system.


Result : 
convoy-efs_convoy-efs-storagepool_1 is running well :

> 17/09/2016 16:40:27Waiting for metadata
> 17/09/2016 16:40:27time="2016-09-17T14:40:27Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
> 17/09/2016 16:40:29time="2016-09-17T14:40:29Z" level=info msg="Socket file: /host/var/run/convoy-convoy-efs.sock"
> 17/09/2016 16:40:32time="2016-09-17T14:40:32Z" level=info msg="Initializing event router" workerCount=10
> 17/09/2016 16:40:33time="2016-09-17T14:40:33Z" level=info msg="Connection established"
> 17/09/2016 16:40:34time="2016-09-17T14:40:34Z" level=debug msg="storagepool event [ad66ec8b-c80b-462e-8d6a-66d948675*** bd5accba-cfec-4e50-bd4c-b5355d9f5***]"

Both convoy-efs_convoy-efs_1 and convoy-efs_convoy-efs_2 give this message :

> 17/09/2016 16:49:47time="2016-09-17T14:49:47Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/2591/ns/mnt -F -- /var/lib/docker/devicemapper/mnt/bccf4a527b7b88da898bd934197d052bf8afaa13cab7bee2d65f53830dc2bb96/rootfs/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-efs-ce33c079-4a39-469f-8434-45fdb10bebcb -- /launch volume-agent-efs-internal 2591]"
> 17/09/2016 16:49:47Registering convoy socket at /var/run/convoy-convoy-efs.sock
> 17/09/2016 16:49:47Mounting at: /var/lib/rancher/convoy/convoy-efs-ce33c079-4a39-469f-8434-45fdb10bebcb/mnt
> 17/09/2016 16:49:47Mounting nfs. Command: mount -t nfs -o nfsvers=4.1 us-west-2a.fs-d1f2***.efs.us-west-2.amazonaws.com:/ /var/lib/rancher/convoy/convoy-efs-ce33c079-4a39-469f-8434-45fdb10bebcb/mnt
> 17/09/2016 16:54:05mount.nfs: Connection timed out

**Comment by ebuildy** [comment]
@npjonath you got a "timed out", check that the security groupe rules allows your machine to access to EFS: http://docs.aws.amazon.com/efs/latest/ug/security-considerations.html.

**Comment by daankets** [comment]
Same here. All services/containers are stuck in initialising, there are no clear error messages. The storage pool is 'Active' in the dashboard.

```
19/09/2016 13:00:23Waiting for metadata
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/25152/ns/mnt -F -- /var/lib/docker/aufs/mnt/34897ecf127d04af80c8b9afd1f8e55c3d5cfc0853d43d7ac4a7f8b178f5a258/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0 -- /launch volume-agent-nfs-internal 25152]"
19/09/2016 13:00:24Registering convoy socket at /var/run/convoy-convoy-nfs.sock
19/09/2016 13:00:24Mounting at: /var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0/mnt
19/09/2016 13:00:24Mounting nfs. Command: mount -t nfs -o nfsvers=4 obfuscated.host:/storage/somemount /var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0/mnt
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0/mnt]"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Got: ignore-docker-delete true"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Got: create-on-docker-mount true"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Got: drivers [vfs]"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-nfs.sock daemon --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0/mnt --ignore-docker-delete=true --create-on-docker-mount=true --root=/var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0 --drivers=vfs]"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-nfs-9c94f810-f273-4766-a4b5-bac5e670cbf0"
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering GET, /info" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering GET, /volumes/" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering GET, /backups/list" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering POST, /backups/create" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering DELETE, /backups" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon
19/09/2016 13:00:24time="2016-09-19T11:00:24Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon
```

**Comment by npjonath** [comment]
@ebuildy indeed, I forgot a rules. But now still stuck at initialization process like the others.

**Comment by ebuildy** [comment]
Welcome :-) à good sysadmin told me its much better to declare NFS mount in
fstab, i do that, it took 2 minutes and it works fine.

**Comment by dalareo** [comment]
I am using docker-nfs as NFS server and Convoy-NFS from official catalog. I get:

    9/25/2016 5:48:58 PMWaiting for metadata
    9/25/2016 5:49:00 PMtime="2016-09-25T15:49:00Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/21890/ns/mnt -F -- /var/lib/docker/aufs/mnt/92a90b8886fcc95fa179c737ce16d7da267e72904ef3e2a63dc8629d8f217f83/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-9cc7a338-0aaa-4508-9a5b-538729433d95 -- /launch volume-agent-nfs-internal 21890]"
    9/25/2016 5:49:00 PMRegistering convoy socket at /var/run/convoy-convoy-nfs.sock
    9/25/2016 5:49:00 PMMounting at: /var/lib/rancher/convoy/convoy-nfs-9cc7a338-0aaa-4508-9a5b-538729433d95/mnt
    9/25/2016 5:49:00 PMMounting nfs. Command: mount -t nfs -o proto=tcp,port=2049,nfsvers=4 10.42.118.232:/ /var/lib/rancher/convoy/convoy-nfs-9cc7a338-0aaa-4508-9a5b-538729433d95/mnt
    9/25/2016 5:51:05 PMmount.nfs: Connection timed out

I'm not sure it is the same bug. I am using Rancher 1.14. I follow the steps as explained at: http://rancher.com/setting-shared-volumes-convoy-nfs/

**Comment by ebuildy** [comment]
Timeout could mean à security group issue, try to mount manually to double
check it.

Le 25 sept. 2016 5:57 PM, "David A. Lareo" <notifications@github.com> a
écrit :

**Comment by dalareo** [comment]
I found out that the problem was with my NFS-server. I used dockerized version from https://github.com/cpuguy83/docker-nfs-server but there is a bug solved here: https://github.com/cpuguy83/docker-nfs-server/commit/b8410bb3e13958e312c8eb92206a8d353fd525dc

**Comment by SantoDE** [comment]
I'm stuck with initializing as well

`7.10.2016 16:18:18Waiting for metadata
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/975/ns/mnt -F -- /var/lib/docker/overlay/8e4594da8b0e8130258aaf86d4b8aaa51979f751e4dff6f376211618cb533afa/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667 -- /launch volume-agent-nfs-internal 975]"
7.10.2016 16:18:19Registering convoy socket at /var/run/convoy-convoy-nfs.sock
7.10.2016 16:18:19Mounting at: /var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667/mnt
7.10.2016 16:18:19Mounting nfs. Command: mount -t nfs -o ro 10.10.10.3:/mnt/nfs /var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667/mnt
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Got: ignore-docker-delete true"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Got: create-on-docker-mount true"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Got: drivers [vfs]"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Got: driver-opts [vfs.path=/var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667/mnt]"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/convoy-convoy-nfs.sock daemon --ignore-docker-delete=true --create-on-docker-mount=true --root=/var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667 --drivers=vfs --driver-opts=vfs.path=/var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667/mnt]"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg= driver=vfs driver_opts=map[vfs.path:/var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667/mnt] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-nfs-b13d3089-44cd-4905-8928-686e50bb1667"
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg= driver=vfs event=init pkg=daemon reason=complete
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering GET, /info" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering GET, /volumes/list" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering GET, /volumes/" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering GET, /snapshots/" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering GET, /backups/list" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering GET, /backups/inspect" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering POST, /volumes/create" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering POST, /volumes/mount" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering POST, /volumes/umount" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering POST, /snapshots/create" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering POST, /backups/create" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering DELETE, /backups" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering DELETE, /volumes/" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering DELETE, /snapshots/" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Remove" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Mount" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Unmount" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Path" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Get" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.List" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /Plugin.Activate" pkg=daemon
7.10.2016 16:18:19time="2016-10-07T14:18:19Z" level=debug msg="Registering plugin handler POST, /VolumeDriver.Create" pkg=daemon`

Im a little lost to be honest

**Comment by Joeasaurus** [comment]
I'm seeing this with Convoy-EFS. Specifically it happens after I boot a second machine and join it to the environment. Since `io.rancher.scheduler.global = true`, a second container starts on the new host and both then get stuck in initialising. 

What's interesting is I have killed all the extra hosts and this new one is stuck initialising all on it's own. I tried to have a little look around and indeed the socket appears to be missing.

I'm not above rebooting the whole machine or just the container, but neither seems to work. The container just comes back into initialising with no socket again.

This is quite annoying as a lot of my other services depend on the mount point :(

**Comment by npjonath** [comment]
I'm still not able to use Convoy-EFS like @Joeasaurus with release and master branch of rancher. the only way I manage to use it is by running only one host per environment. It's make the job for my usecase, but we lost possibilities to scale up our infrastructure. My security group are good according to the documentation and previous recommandation.

**Comment by ebuildy** [comment]
NFS must be mounted on /etc/fstab, this is the good way to do it.

**Comment by npjonath** [comment]
@ebuildy Ok but what's the point to make a Convoy-EFS module for Rancher if we need to set up manually for every host on /etc/fstab?

**Comment by ebuildy** [comment]
I don't know, I asked the question to many sys-admin, all replied "you must mount via fstab, else you will have bugs", and you have bugs!

It took a few minutes to setup fstab, just a line to append ! Then you can safely reboot and no more issues.

There are a ton of NFS Docker images, I tried many, spent time for nothing, then I mount on fstab and it works..

**Comment by npjonath** [comment]
@ebuildy I understand, it looks like a good workaround for development purpose and indeed it's seems to make the job. But this solution cannot be used in production with autoscalling group (one example of usecase, but not the only one). So until we get a fix, rancher for AWS Host is almost useless for us.

**Comment by ebuildy** [comment]
@npjonath production ?? I worked for maybe 50 companies, and always saw NFS mount in fstab, btw, with AWS, I always read documention from Amazon, and:

http://docs.aws.amazon.com/efs/latest/ug/mount-fs-auto-mount-onreboot.html

et Voila! Also, you can easily create your own image on AWS with fstab already setup.

**Comment by Joeasaurus** [comment]
As far as I'm concerned, fstab is like cron for mountpoints. There should be no difference between a manual `mount -t <> -o <>` and an fstab mount, one simply happens at boot time.

Aside that, the AWS docs on that page also sat this:
>Do not copy the contents of your /etc/fstab file between EC2 instances in different Availability Zones. Each file system has a unique DNS name for each Availability Zone in which you have created a mount target. For more information about how to get the right DNS name for your mount point, see Mounting with a DNS Name.

So now I have to have an image per fstab entry, or some kind of boot-time logic....wait a minute.

Now, boot time logic could work if it's only the entry to fstab that matters, not the fact that we mount it during boot. In which case the Convoy manager/container whatever could edit that file.

Anyway, the problem doesn't really feel like "I can't mount it" or anything though. It feels to me more like "It's working but convoy can't healthcheck properly", so the containers stay in initialising. Maybe due to some kind of single-instance lock or something? Or maybe there's an extra label we should be putting on the containers that has forgotten to be documented, rather than simply "schedule globally".

In fact I wonder if this is actually a healthcheck issue in a more general sense, or some "messy state" persisting on the host after convoy container issues.

For instance I now have both efs-agents (one per Host) AND the storagepool instance in initializing state, and (I think subsequently) my gitlab instance is stuck initializing. But here you can see that gitlab is happily mounting and using volumes (df -h)
```
eu-west-1b.fs-id-here.efs.eu-west-1.amazonaws.com://gitlab-log  8.0E  1.8G  8.0E   1% /var/log/gitlab
```

This appears to be the case regardless of a reboot of any component listed. So either it's all working perfectly and Rancher just needs to be told that, so it can change to Active, or the mountpoints are working first time and then remaining mounted...possibly also leaving some lock data around that stops the healthchecks succeeding?

If anyone would like to observe this or poke around, I'd be more than happy to get a little demo sandbox running :)

**Comment by STRML** [comment]
Can replicate this pretty easily on a few DO instances. Running https://hub.docker.com/r/strml/docker-nfs-server/ on one (this is simply a fork of docker-nfs-server that fixes the `/etc/services` bug). All volumes are actually mounting properly, everything is working fine, just appears something is not health-checking.

I can confirm that removing the health check gets these things green. But I can curl port 10241 from all over the network, so I'm not sure what the issue is. Perhaps the response isn't formatted properly?

**Comment by STRML** [comment]
Any convoy-nfs agent that was on the same host as the rancher server had network issues and I was unable to curl 10241 from it. I set the rancher server host to inactive and relaunched convoy-nfs; all convoy-nfs services are now green. I've verified this across hosts and including convoy-agent v0.9.0 and v0.12.0.

So, in short, as we've seen in other issues, don't launch containers on the rancher server.

**Comment by sun-meihouwang** [comment]
Exactly the same logs than @anibalaguirreconsultora .
The setup has 4 hosts:
- 1 for the rancher server (v1.1.3)
- 2 rancher hosts (agent-instance:v0.8.3)
- 1 nfs server
Is there a workaround to this problem?

**Comment by n-scope** [comment]
Exactly same logs as @anibalaguirreconsultora and @sun-meihouwang, but in a device mapper config. (Problem does not occur in loopback)

**Comment by yasker** [comment]
Please use Rancher-NFS for Rancher integration in the future.

We've deprecated `convoy-nfs` for Rancher, and wrote `Rancher-NFS` to replace it.

See:

https://github.com/rancher/storage
https://github.com/rancher/storage/tree/master/package/nfs
